version: '3.8'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MY_ENVIRONMENT=Development
    depends_on:
      - db

  nginx:
    image: nginx:1.25.3
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-123}
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "until ping -c1 backend &>/dev/null; do echo 'Waiting for backend...'; sleep 1; done; nginx -g 'daemon off;'"]

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
