version: '3.8'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - teya-dev-network

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MY_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_DATABASE=test
    depends_on:
      - db
    networks:
      - teya-dev-network

  nginx:
    image: nginx:1.25.3
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-123}
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "until ping -c1 backend &>/dev/null; do echo 'Waiting for backend...'; sleep 1; done; nginx -g 'daemon off;'"]
    networks:
      - teya-dev-network

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - teya-dev-network

networks:
  teya-dev-network:
    name: teya-dev-network
    driver: bridge