version: '3.8'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - teya-dev-network

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MY_ENVIRONMENT=Development
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_DATABASE=test
    depends_on:
      - db
    links:
      - db
    networks:
      - teya-dev-network

  nginx:
    image: nginx:1.25.3
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-123}
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "until ping -c1 backend &>/dev/null; do echo 'Waiting for backend...'; sleep 1; done; nginx -g 'daemon off;'"]
    networks:
      - teya-dev-network

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/db_dev:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - teya-dev-network
    hostname: db

  migration:
    image: backend:latest
    command: >
      /bin/sh -c "while ! /usr/local/bin/wait-for-it.sh db:5432 -t 30; do
          echo 'Waiting for database availability...';
          sleep 5;
      done;
      npm run typeorm migration:run"
    links:
      - db
    depends_on:
      - db
    networks:
      - teya-dev-network
    environment:
      - MY_ENVIRONMENT=Development
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_DATABASE=test

networks:
  teya-dev-network:
    name: teya-dev-network
    driver: bridge